---
- name: install Apache and upload web page
  hosts: all
  become: yes

  vars:
    source_file: ./website/index.html
    destin_file: /var/www/html

  tasks:
  - name: check  Linux Version
    debug: var=ansible_os_family

  - block: ########### For RadHat #########

      - name: install Apache for RadHat
        yum: name=httpd state=latest

      - name: copy homepage file to website
        copy: src={{ source_file }} dest={{ destin_file }} mode=0664
        notify: restart Apache RedHat

      - name: start webserver and enable RedHat
        service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - block: ########### For Ubuntu #########

      - name: install Apache for Ubuntu
        apt: name=apache2  state=latest

      - name: copy homepage file to website
        copy: src={{ source_file }} dest={{ destin_file }} mode=0664
        notify: restart Apache Ubuntu

      - name: start webserver and enable Ubuntu
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: restart Apache RedHat
    service: name=httpd state=restarted

  - name: restart Apache Ubuntu
    service: name=apache2 state=restarted
...
